" disable vi compatibility
set nocompatible

" setup general look of vim
set laststatus=2          " show powerline always
set number                " line numbers
syntax on                 " syntax highlighting
filetype on
filetype plugin on
filetype indent on
set wildmenu
set wildmode=list:longest
set fillchars=eob:\       " hide EndOfBuffer characters (tilde)
" tab settings
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
" YouCompleteMe settings
" set completeopt-=preview " disable preview pane at the top
" let g:ycm_add_preview_to_completeopt=0
" NERDTree settings
" autocmd VimEnter * NERDTree | wincmd p " Start NERDTree and put the cursor back in the other window.

" keybindings
" cursor movement
noremap ; l
noremap l k
noremap k j
noremap j h
noremap h <Nop>
" NERDTree
nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n>     :NERDTreeMirror<CR>:NERDTreeFocus<CR>
nnoremap <C-t>     :NERDTreeToggle<CR>
nnoremap <C-f>     :NERDTreeFind<CR>
