#!/bin/sh
# Layout
yabai -m config layout bsp
yabai -m config window_placement second_child

# Gaps
gaps=10
yabai -m config top_padding $gaps
yabai -m config bottom_padding $gaps
yabai -m config left_padding $gaps
yabai -m config right_padding $gaps
yabai -m config window_gap $gaps

# Window Opacity
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

# Focus
yabai -m config focus_follows_mouse autoraise
yabai -m config mouse_follows_focus off

# Animations
yabai -m config window_animation_duration 0.0
yabai -m config window_animation_easing ease_out_circ

# Apply config to all existing windows
yabai -m rule --apply

